name: Publish

on:
  workflow_run:
    workflows: ["Test"]
    branches: [main]
    types:
      - completed

env:
  IMAGE_NAME: "${{ github.repository }}:latest"

jobs:
  publish:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Generate docker tag
        run: |
          git fetch --force --tags
          UNIQUE_ID=$(git describe --tags --always)
          IMAGE_VERSION=$(git tag | tail -1)
          UNIQUE_IMAGE_TAG="${{ github.repository }}:${IMAGE_VERSION}-${UNIQUE_ID}"
          echo "UNIQUE_IMAGE_TAG=$UNIQUE_IMAGE_TAG" >> $GITHUB_ENV
      - name: Show docker tag
        run: echo "UNIQUE_IMAGE_TAG=${{ env.UNIQUE_IMAGE_TAG }}"
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}
            ${{ env.UNIQUE_IMAGE_TAG }}
