name: Test

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [main]
  schedule:
    - cron: "10 02 * * 0" # every Sunday at 2:10 AM UTC

jobs:
  docker-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Run dockerlint
        run: |
          npm install -g dockerlint
          dockerlint Dockerfile
  docker-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Docker build
        run: docker build -t netcheck:latest .
      - name: Run CST
        run: |
          curl -LO https://storage.googleapis.com/container-structure-test/latest/container-structure-test-linux-amd64
          chmod +x container-structure-test-linux-amd64
          mv container-structure-test-linux-amd64 /usr/local/bin/container-structure-test
          container-structure-test test --image netcheck:latest --config cst-config.yaml
      - name: Check container runs
        run: |
          docker run -d --name netcheck netcheck:latest
          docker ps | grep netcheck
      - name: Check nginx page
        run: |
          netcheck_ip=$(docker inspect -f \
            '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' netcheck)
          curl http://${netcheck_ip}
